// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AccountApplicationInfo struct {
	Id                int64  `json:"id"`                // 申请ID
	ApplicationNumber string `json:"applicationNumber"` // 申请单号
	CustomerId        int64  `json:"customerId"`        // 客户ID
	CustomerName      string `json:"customerName"`      // 客户姓名
	CustomerEmail     string `json:"customerEmail"`     // 客户邮箱
	CustomerPhone     string `json:"customerPhone"`     // 客户电话
	Currency          string `json:"currency"`          // 币种
	Status            string `json:"status"`            // 状态
	StatusText        string `json:"statusText"`        // 状态文本
	Materials         string `json:"materials"`         // 申请材料（JSON格式）
	ApplicationTime   string `json:"applicationTime"`   // 申请时间
	AuditorId         int64  `json:"auditorId"`         // 审核人ID
	AuditorName       string `json:"auditorName"`       // 审核人姓名
	AuditTime         string `json:"auditTime"`         // 审核时间
	AuditNote         string `json:"auditNote"`         // 审核意见
	AuditResult       string `json:"auditResult"`       // 审核结果
	Note              string `json:"note"`              // 备注
	CreatedAt         string `json:"createdAt"`         // 创建时间
	UpdatedAt         string `json:"updatedAt"`         // 更新时间
}

type AccountApplicationListData struct {
	Total int64                    `json:"total"`
	List  []AccountApplicationInfo `json:"list"`
}

type AccountBrief struct {
	Id                    int64  `json:"id"`                    // 账户ID
	AccountNumber         string `json:"accountNumber"`         // 账户号
	Currency              string `json:"currency"`              // 币种
	Status                int32  `json:"status"`                // 状态
	StatusText            string `json:"statusText"`            // 状态文本
	Balance               string `json:"balance"`               // 账户余额
	AvailableBalance      string `json:"availableBalance"`      // 可用余额
	FrozenBalance         string `json:"frozenBalance"`         // 冻结余额
	CustomerId            int64  `json:"customerId"`            // 客户ID
	CustomerName          string `json:"customerName"`          // 客户姓名
	CustomerEmail         string `json:"customerEmail"`         // 客户邮箱
	CustomerPhone         string `json:"customerPhone"`         // 客户电话
	TransactionCount      int64  `json:"transactionCount"`      // 交易笔数
	TotalDepositAmount    string `json:"totalDepositAmount"`    // 累计存款金额
	TotalWithdrawalAmount string `json:"totalWithdrawalAmount"` // 累计提现金额
	LastTransactionAt     string `json:"lastTransactionAt"`     // 最后交易时间
	AccountOpeningDate    string `json:"accountOpeningDate"`    // 开户日期
	CreatedAt             string `json:"createdAt"`             // 创建时间
	UpdatedAt             string `json:"updatedAt"`             // 更新时间
}

type AccountDetail struct {
	Id                      int64  `json:"id"`                      // 账户ID
	AccountNumber           string `json:"accountNumber"`           // 账户号
	Currency                string `json:"currency"`                // 币种
	Status                  int32  `json:"status"`                  // 状态
	StatusText              string `json:"statusText"`              // 状态文本
	Balance                 string `json:"balance"`                 // 账户余额
	AvailableBalance        string `json:"availableBalance"`        // 可用余额
	FrozenBalance           string `json:"frozenBalance"`           // 冻结余额
	CustomerId              int64  `json:"customerId"`              // 客户ID
	CustomerName            string `json:"customerName"`            // 客户姓名
	CustomerEmail           string `json:"customerEmail"`           // 客户邮箱
	CustomerPhone           string `json:"customerPhone"`           // 客户电话
	CustomerAddress         string `json:"customerAddress"`         // 客户地址
	CustomerType            string `json:"customerType"`            // 客户类型
	KycStatus               string `json:"kycStatus"`               // KYC状态
	TransactionCount        int64  `json:"transactionCount"`        // 交易笔数
	TotalDepositAmount      string `json:"totalDepositAmount"`      // 累计存款金额
	TotalWithdrawalAmount   string `json:"totalWithdrawalAmount"`   // 累计提现金额
	TotalFeeAmount          string `json:"totalFeeAmount"`          // 累计手续费
	DailyTransactionLimit   string `json:"dailyTransactionLimit"`   // 日交易限额
	MonthlyTransactionLimit string `json:"monthlyTransactionLimit"` // 月交易限额
	LastTransactionAt       string `json:"lastTransactionAt"`       // 最后交易时间
	AccountOpeningDate      string `json:"accountOpeningDate"`      // 开户日期
	CreatedAt               string `json:"createdAt"`               // 创建时间
	UpdatedAt               string `json:"updatedAt"`               // 更新时间
}

type AccountListData struct {
	Total int64          `json:"total"`
	List  []AccountBrief `json:"list"`
}

type AddAddressReq struct {
	Id      int64  `path:"id"`             // 钱包ID
	Address string `json:"address"`        // 提现地址
	Label   string `json:"label,optional"` // 备注
}

type AddressInfo struct {
	Id        int64  `json:"id"`        // 地址ID
	Address   string `json:"address"`   // 地址
	Label     string `json:"label"`     // 备注
	CreatedAt int64  `json:"createdAt"` // 创建时间
}

type BaseResp struct {
	Code    int32  `json:"code"`    // 响应码 0-成功 非0-失败
	Message string `json:"message"` // 响应消息
}

type CancelWithdrawalReq struct {
	Id int64 `path:"id"` // 提现ID
}

type CaptchaData struct {
	CaptchaId    string `json:"captchaId"`    // 验证码ID 有效期5分钟
	CaptchaImage string `json:"captchaImage"` // 验证码图片base64
	ExpireAt     int64  `json:"expireAt"`     // 过期时间戳（毫秒）
}

type CaptchaResp struct {
	Code    int32       `json:"code"`    // 响应码
	Message string      `json:"message"` // 响应消息
	Data    CaptchaData `json:"data"`    // 数据
}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"` // 旧密码
	NewPassword string `json:"newPassword"` // 新密码 长度8-20位
}

type CountryInfo struct {
	Id          int64  `json:"id"`          // ID
	Code        string `json:"code"`        // 国家代码
	Name        string `json:"name"`        // 国家名称
	NameEn      string `json:"nameEn"`      // 英文名称
	Currency    string `json:"currency"`    // 货币代码
	PhoneCode   string `json:"phoneCode"`   // 电话区号
	Sort        int    `json:"sort"`        // 排序
	Status      int    `json:"status"`      // 状态
	Description string `json:"description"` // 描述
	CreatedAt   int64  `json:"createdAt"`   // 创建时间
	UpdatedAt   int64  `json:"updatedAt"`   // 更新时间
}

type CreateAccountApplicationReq struct {
	CustomerId int64  `json:"customerId"` // 客户ID
	Currency   string `json:"currency"`   // 币种
	Materials  string `json:"materials"`  // 资料JSON
}

type CreateAccountApplicationResp struct {
	Code    int32                  `json:"code"`    // 响应码
	Message string                 `json:"message"` // 响应消息
	Data    AccountApplicationInfo `json:"data"`    // 数据
}

type CreateAgentReq struct {
	Email           string  `json:"email"`           // 邮箱
	ExchangeFeeRate string  `json:"exchangeFeeRate"` // 换汇手续费率
	WithdrawFee     string  `json:"withdrawFee"`     // 提现手续费
	CountryIds      []int64 `json:"countryIds"`      // 授权国家ID列表
	Note            string  `json:"note,optional"`   // 备注
}

type CreateAgentResp struct {
	Code    int32    `json:"code"`    // 响应码
	Message string   `json:"message"` // 响应消息
	Data    UserInfo `json:"data"`    // 用户信息
}

type CreateCustomerReq struct {
	FirstName       string `json:"firstName"`                // 名
	LastName        string `json:"lastName"`                 // 姓
	Phone           string `json:"phone"`                    // 电话
	Email           string `json:"email"`                    // 邮箱
	Address         string `json:"address"`                  // 地址
	IdNumber        string `json:"idNumber,optional"`        // 身份证/护照
	BusinessLicense string `json:"businessLicense,optional"` // 营业执照
}

type CreateCustomerResp struct {
	Code    int32        `json:"code"`    // 响应码
	Message string       `json:"message"` // 响应消息
	Data    CustomerInfo `json:"data"`    // 数据
}

type CreateInviteReq struct {
	TargetUserType  string  `json:"targetUserType"`                  // 目标用户类型：agent、manager、customer
	ExchangeFeeRate string  `json:"exchangeFeeRate"`                 // 换汇手续费率
	WithdrawFee     string  `json:"withdrawFee"`                     // 提现手续费
	CountryIds      []int64 `json:"countryIds"`                      // 授权国家ID列表
	ExpireHours     int32   `json:"expireHours,default=24,optional"` // 有效期 默认24小时
	Remark          string  `json:"remark,optional"`                 // 备注
}

type CreateInviteResp struct {
	Code    int32      `json:"code"`    // 响应码
	Message string     `json:"message"` // 响应消息
	Data    InviteInfo `json:"data"`    // 数据
}

type CreateManagerReq struct {
	Email           string  `json:"email"`           // 邮箱
	ExchangeFeeRate string  `json:"exchangeFeeRate"` // 换汇手续费率
	WithdrawFee     string  `json:"withdrawFee"`     // 提现手续费
	CountryIds      []int64 `json:"countryIds"`      // 授权国家ID列表
	Note            string  `json:"note,optional"`   // 备注
}

type CreateManagerResp struct {
	Code    int32    `json:"code"`    // 响应码
	Message string   `json:"message"` // 响应消息
	Data    UserInfo `json:"data"`    // 用户信息
}

type CreateWithdrawalReq struct {
	WalletId     int64  `json:"walletId"`     // 钱包ID
	AddressId    int64  `json:"addressId"`    // 提现地址ID
	Amount       string `json:"amount"`       // 提现金额（USDT）
	Symbol       string `json:"symbol"`       // 币种 USDT
	FundPassword string `json:"fundPassword"` // 资金密码
}

type CreateWithdrawalResp struct {
	Code    int32          `json:"code"`
	Message string         `json:"message"`
	Data    WithdrawalInfo `json:"data"`
}

type CurrencyStat struct {
	Currency         string `json:"currency"`         // 币种
	DepositAmount    string `json:"depositAmount"`    // 存款金额
	WithdrawalAmount string `json:"withdrawalAmount"` // 提现金额
	FeeAmount        string `json:"feeAmount"`        // 手续费金额
	TransactionCount int64  `json:"transactionCount"` // 交易笔数
}

type CustomerInfo struct {
	Id        int64  `json:"id"`        // 客户ID
	FirstName string `json:"firstName"` // 名
	LastName  string `json:"lastName"`  // 姓
	Phone     string `json:"phone"`     // 电话
	Email     string `json:"email"`     // 邮箱
	Address   string `json:"address"`   // 地址
	CreatedAt int64  `json:"createdAt"` // 创建时间
}

type CustomerListData struct {
	Total int64          `json:"total"` // 总数
	List  []CustomerInfo `json:"list"`  // 列表
}

type CustomerStat struct {
	CustomerId       int64  `json:"customerId"`       // 客户ID
	CustomerName     string `json:"customerName"`     // 客户姓名
	CustomerEmail    string `json:"customerEmail"`    // 客户邮箱
	TotalDeposit     string `json:"totalDeposit"`     // 总存款
	TotalWithdrawal  string `json:"totalWithdrawal"`  // 总提现
	TransactionCount int64  `json:"transactionCount"` // 交易笔数
}

type CustomersReportData struct {
	TotalDeposit     string         `json:"totalDeposit"`     // 总存款
	TotalWithdrawal  string         `json:"totalWithdrawal"`  // 总提现
	TotalFee         string         `json:"totalFee"`         // 总手续费
	CustomerCount    int64          `json:"customerCount"`    // 客户数量
	TransactionCount int64          `json:"transactionCount"` // 交易笔数
	CurrencyStats    []CurrencyStat `json:"currencyStats"`    // 币种统计
	MonthlyStats     []MonthlyStat  `json:"monthlyStats"`     // 月度统计
	TopCustomers     []CustomerStat `json:"topCustomers"`     // 活跃客户统计
}

type DataResp struct {
	Code    int32       `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"` // 响应数据
}

type DeleteAddressReq struct {
	Id        int64 `path:"id"`        // 钱包ID
	AddressId int64 `path:"addressId"` // 地址ID
}

type FeeSettings struct {
	ExchangeFeeRate string `json:"exchangeFeeRate"` // 换汇手续费率
	WithdrawFee     string `json:"withdrawFee"`     // 提现手续费
}

type GetAccountApplicationResp struct {
	Code    int32                  `json:"code"`
	Message string                 `json:"message"`
	Data    AccountApplicationInfo `json:"data"`
}

type GetAccountResp struct {
	Code    int32         `json:"code"`
	Message string        `json:"message"`
	Data    AccountDetail `json:"data"`
}

type GetBalanceResp struct {
	Code    int32             `json:"code"`
	Message string            `json:"message"`
	Data    WalletBalanceInfo `json:"data"`
}

type GetCustomerResp struct {
	Code    int32        `json:"code"`    // 响应码
	Message string       `json:"message"` // 响应消息
	Data    CustomerInfo `json:"data"`    // 数据
}

type GetCustomersReportReq struct {
	StartTime int64  `form:"startTime,optional"` // 开始时间
	EndTime   int64  `form:"endTime,optional"`   // 结束时间
	Currency  string `form:"currency,optional"`  // 币种筛选
}

type GetCustomersReportResp struct {
	Code    int32               `json:"code"`    // 响应码
	Message string              `json:"message"` // 响应消息
	Data    CustomersReportData `json:"data"`    // 数据
}

type GetFeeSettingsResp struct {
	Code    int32       `json:"code"`    // 响应码
	Message string      `json:"message"` // 响应消息
	Data    FeeSettings `json:"data"`    // 数据
}

type GetInviteResp struct {
	Code    int32      `json:"code"`    // 响应码
	Message string     `json:"message"` // 响应消息
	Data    InviteInfo `json:"data"`    // 数据
}

type GetMyReportReq struct {
	StartTime int64  `form:"startTime,optional"` // 开始时间
	EndTime   int64  `form:"endTime,optional"`   // 结束时间
	Currency  string `form:"currency,optional"`  // 币种筛选
}

type GetMyReportResp struct {
	Code    int32        `json:"code"`    // 响应码
	Message string       `json:"message"` // 响应消息
	Data    MyReportData `json:"data"`    // 数据
}

type GetSubUserReportReq struct {
	UserId           int64  `path:"userId"`                                  // 用户ID
	StartTime        int64  `form:"startTime,optional"`                      // 开始时间
	EndTime          int64  `form:"endTime,optional"`                        // 结束时间
	Currency         string `form:"currency,optional"`                       // 币种筛选
	IncludeSubLevels bool   `form:"includeSubLevels,default=false,optional"` // 是否包含子级的下级
}

type GetSubUserReportResp struct {
	Code    int32             `json:"code"`    // 响应码
	Message string            `json:"message"` // 响应消息
	Data    SubUserReportData `json:"data"`    // 数据
}

type GetSubUsersReq struct {
	Id               int64  `path:"id"`                                      // 用户ID
	Page             int64  `form:"page,default=1,optional"`                 // 页码
	PageSize         int64  `form:"pageSize,default=10,optional"`            // 每页数量
	UserType         string `form:"userType,optional"`                       // 用户类型筛选
	IncludeSubLevels bool   `form:"includeSubLevels,default=false,optional"` // 是否包含子级的下级
}

type GetSummaryResp struct {
	Code    int32       `json:"code"`
	Message string      `json:"message"`
	Data    SummaryInfo `json:"data"`
}

type GetTransactionResp struct {
	Code    int32             `json:"code"`
	Message string            `json:"message"`
	Data    TransactionDetail `json:"data"`
}

type GetUserResp struct {
	Code    int32    `json:"code"`    // 响应码
	Message string   `json:"message"` // 响应消息
	Data    UserInfo `json:"data"`    // 数据
}

type GetWalletResp struct {
	Code    int32        `json:"code"`
	Message string       `json:"message"`
	Data    WalletDetail `json:"data"`
}

type GetWithdrawalResp struct {
	Code    int32          `json:"code"`
	Message string         `json:"message"`
	Data    WithdrawalInfo `json:"data"`
}

type IdReq struct {
	Id int64 `path:"id"` // 资源ID
}

type InviteInfo struct {
	Id              int64   `json:"id"`                    // ID
	InviteCode      string  `json:"inviteCode"`            // 邀请码
	InviteUrl       string  `json:"inviteUrl"`             // 注册链接
	TargetUserType  string  `json:"targetUserType"`        // 目标用户类型
	ExchangeFeeRate string  `json:"exchangeFeeRate"`       // 换汇手续费率
	WithdrawFee     string  `json:"withdrawFee"`           // 提现手续费
	CountryIds      []int64 `json:"countryIds"`            // 授权国家ID列表
	Status          int32   `json:"status"`                // 0-未使用 1-已使用 2-已撤销 3-已过期
	ExpireAt        int64   `json:"expireAt"`              // 过期时间
	UsedAt          int64   `json:"usedAt,optional"`       // 使用时间
	UsedByUserId    int64   `json:"usedByUserId,optional"` // 使用人用户ID
	UsedByEmail     string  `json:"usedByEmail,optional"`  // 使用人邮箱
	CreatedAt       int64   `json:"createdAt"`             // 创建时间
	Remark          string  `json:"remark,optional"`       // 备注
}

type InviteListData struct {
	Total int64        `json:"total"` // 总记录数
	List  []InviteInfo `json:"list"`  // 列表
}

type ListAccountApplicationsReq struct {
	Page       int64  `form:"page,default=1,optional"`      // 页码
	PageSize   int64  `form:"pageSize,default=10,optional"` // 每页数量
	Status     string `form:"status,optional"`              // 状态筛选
	CustomerId int64  `form:"customerId,optional"`          // 客户ID筛选
	Currency   string `form:"currency,optional"`            // 币种筛选
	StartTime  string `form:"startTime,optional"`           // 申请开始时间
	EndTime    string `form:"endTime,optional"`             // 申请结束时间
	Keyword    string `form:"keyword,optional"`             // 关键词搜索（申请单号、客户姓名）
}

type ListAccountApplicationsResp struct {
	Code    int32                      `json:"code"`
	Message string                     `json:"message"`
	Data    AccountApplicationListData `json:"data"`
}

type ListAccountsReq struct {
	Page       int64  `form:"page,default=1,optional"`      // 页码
	PageSize   int64  `form:"pageSize,default=10,optional"` // 每页数量
	Currency   string `form:"currency,optional"`            // 币种筛选
	Status     int32  `form:"status,optional"`              // 状态筛选
	CustomerId int64  `form:"customerId,optional"`          // 客户ID筛选
	StartTime  string `form:"startTime,optional"`           // 开户开始时间
	EndTime    string `form:"endTime,optional"`             // 开户结束时间
	Keyword    string `form:"keyword,optional"`             // 关键词搜索（账户号、客户姓名）
}

type ListAccountsResp struct {
	Code    int32           `json:"code"`
	Message string          `json:"message"`
	Data    AccountListData `json:"data"`
}

type ListAddressesResp struct {
	Code    int32         `json:"code"`
	Message string        `json:"message"`
	Data    []AddressInfo `json:"data"`
}

type ListCustomersReq struct {
	Page     int64  `form:"page,default=1,optional"`      // 页码
	PageSize int64  `form:"pageSize,default=10,optional"` // 每页
	Keyword  string `form:"keyword,optional"`             // 关键字
}

type ListCustomersResp struct {
	Code    int32            `json:"code"`    // 响应码
	Message string           `json:"message"` // 响应消息
	Data    CustomerListData `json:"data"`    // 数据
}

type ListInvitesReq struct {
	Page           int64  `form:"page,default=1,optional"`      // 页码
	PageSize       int64  `form:"pageSize,default=10,optional"` // 每页数量
	TargetUserType string `form:"targetUserType,optional"`      // 目标用户类型
	Status         int32  `form:"status,optional"`              // 状态
}

type ListInvitesResp struct {
	Code    int32          `json:"code"`    // 响应码
	Message string         `json:"message"` // 响应消息
	Data    InviteListData `json:"data"`    // 数据
}

type ListTransactionsReq struct {
	Page     int64  `form:"page,default=1,optional"`
	PageSize int64  `form:"pageSize,default=10,optional"`
	Symbol   string `form:"symbol,optional"`
	Type     string `form:"type,optional"` // deposit/withdrawal/transfer
}

type ListTransactionsResp struct {
	Code    int32               `json:"code"`
	Message string              `json:"message"`
	Data    TransactionListData `json:"data"`
}

type ListUsersReq struct {
	Page     int64  `form:"page,default=1,optional"`      // 页码
	PageSize int64  `form:"pageSize,default=10,optional"` // 每页数量
	Keyword  string `form:"keyword,optional"`             // 关键词搜索
	UserType string `form:"userType,optional"`            // 用户类型筛选
	Status   int32  `form:"status,optional"`              // 状态筛选
}

type ListUsersResp struct {
	Code    int32        `json:"code"`    // 响应码
	Message string       `json:"message"` // 响应消息
	Data    UserListData `json:"data"`    // 数据
}

type ListWalletsReq struct {
	Page     int64  `form:"page,default=1,optional"`      // 页码
	PageSize int64  `form:"pageSize,default=10,optional"` // 每页
	Symbol   string `form:"symbol,optional"`              // 币种
}

type ListWalletsResp struct {
	Code    int32          `json:"code"`
	Message string         `json:"message"`
	Data    WalletListData `json:"data"`
}

type ListWithdrawalsReq struct {
	Page     int64  `form:"page,default=1,optional"`
	PageSize int64  `form:"pageSize,default=10,optional"`
	Status   int32  `form:"status,optional"`
	Symbol   string `form:"symbol,optional"`
}

type ListWithdrawalsResp struct {
	Code    int32              `json:"code"`
	Message string             `json:"message"`
	Data    WithdrawalListData `json:"data"`
}

type ManagerInfo struct {
	Id              int64  `json:"id"`              // ID
	Email           string `json:"email"`           // 邮箱
	ExchangeFeeRate string `json:"exchangeFeeRate"` // 换汇手续费率
	WithdrawFee     string `json:"withdrawFee"`     // 提现手续费
	CreatedAt       int64  `json:"createdAt"`       // 创建时间
}

type ManagerInfoResp struct {
	Code    int32       `json:"code"`
	Message string      `json:"message"`
	Data    ManagerInfo `json:"data"`
}

type ManagerLoginData struct {
	Token        string      `json:"token"`        // JWT令牌
	RefreshToken string      `json:"refreshToken"` // 刷新令牌
	ExpiresIn    int64       `json:"expiresIn"`    // 过期时间（秒）
	Manager      ManagerInfo `json:"manager"`      // 客户经理信息
}

type ManagerLoginReq struct {
	Email     string `json:"email"`     // 邮箱
	Password  string `json:"password"`  // 密码
	CaptchaId string `json:"captchaId"` // 图片验证码ID
	Captcha   string `json:"captcha"`   // 图片验证码值
}

type ManagerLoginResp struct {
	Code    int32            `json:"code"`    // 响应码
	Message string           `json:"message"` // 响应消息
	Data    ManagerLoginData `json:"data"`    // 数据
}

type ManagerProfileInfo struct {
	Id              int64   `json:"id"`              // ID
	Name            string  `json:"name"`            // 姓名
	Username        string  `json:"username"`        // 用户名
	Email           string  `json:"email"`           // 邮箱
	Status          int32   `json:"status"`          // 状态
	ExchangeFeeRate float64 `json:"exchangeFeeRate"` // 换汇手续费率
	WithdrawFeeRate float64 `json:"withdrawFeeRate"` // 提现手续费率
	CreatedAt       int64   `json:"createdAt"`       // 创建时间
}

type ManagerProfileResp struct {
	Code    int32              `json:"code"`    // 响应码
	Message string             `json:"message"` // 响应消息
	Data    ManagerProfileInfo `json:"data"`    // 数据
}

type ManagerRegisterReq struct {
	Email      string `json:"email"`      // 邮箱
	Password   string `json:"password"`   // 登录密码
	InviteCode string `json:"inviteCode"` // 邀请码
	EmailCode  string `json:"emailCode"`  // 邮箱验证码
	CaptchaId  string `json:"captchaId"`  // 图片验证码ID
	Captcha    string `json:"captcha"`    // 图片验证码值
}

type MenuInfo struct {
	Id         int64      `json:"id"`                // ID
	Name       string     `json:"name"`              // 名称
	Path       string     `json:"path"`              // 路由/路径
	Icon       string     `json:"icon"`              // 图标
	Component  string     `json:"component"`         // 组件路径
	Role       string     `json:"role"`              // 角色权限
	Label      string     `json:"label"`             // 显示标签
	Alias      string     `json:"alias"`             // 别名路径
	Type       int32      `json:"type"`              // 类型：1-菜单, 2-按钮
	ParentId   int64      `json:"parentId"`          // 父级ID
	Sort       int32      `json:"sort"`              // 排序
	Status     int32      `json:"status"`            // 状态：1-启用, 0-禁用
	StatusText string     `json:"statusText"`        // 状态文本
	CreatedAt  string     `json:"createdAt"`         // 创建时间
	UpdatedAt  string     `json:"updatedAt"`         // 更新时间
	Children   []MenuInfo `json:"children,optional"` // 子菜单
}

type MonthlyStat struct {
	Year             int32  `json:"year"`             // 年份
	Month            int32  `json:"month"`            // 月份
	DepositAmount    string `json:"depositAmount"`    // 存款金额
	WithdrawalAmount string `json:"withdrawalAmount"` // 提现金额
	FeeAmount        string `json:"feeAmount"`        // 手续费金额
	TransactionCount int64  `json:"transactionCount"` // 交易笔数
}

type MyReportData struct {
	UserId           int64          `json:"userId"`           // 用户ID
	UserEmail        string         `json:"userEmail"`        // 用户邮箱
	UserType         string         `json:"userType"`         // 用户类型
	TotalDeposit     string         `json:"totalDeposit"`     // 总存款
	TotalWithdrawal  string         `json:"totalWithdrawal"`  // 总提现
	TotalFee         string         `json:"totalFee"`         // 总手续费
	SubUserCount     int64          `json:"subUserCount"`     // 下级用户数量
	CustomerCount    int64          `json:"customerCount"`    // 客户数量
	TransactionCount int64          `json:"transactionCount"` // 交易笔数
	CurrencyStats    []CurrencyStat `json:"currencyStats"`    // 币种统计
	MonthlyStats     []MonthlyStat  `json:"monthlyStats"`     // 月度统计
}

type PageData struct {
	Total    int64 `json:"total"`    // 总记录数
	Page     int64 `json:"page"`     // 当前页码
	PageSize int64 `json:"pageSize"` // 每页数量
}

type PageReq struct {
	Page     int64 `form:"page,default=1,optional"`      // 页码 默认1
	PageSize int64 `form:"pageSize,default=10,optional"` // 每页数量 默认10 最大100
}

type SendCodeReq struct {
	Email string `json:"email"` // 邮箱
	Scene string `json:"scene"` // 场景 register/reset
}

type SubUserReportData struct {
	UserId           int64               `json:"userId"`           // 用户ID
	UserEmail        string              `json:"userEmail"`        // 用户邮箱
	UserType         string              `json:"userType"`         // 用户类型
	TotalDeposit     string              `json:"totalDeposit"`     // 总存款
	TotalWithdrawal  string              `json:"totalWithdrawal"`  // 总提现
	TotalFee         string              `json:"totalFee"`         // 总手续费
	SubUserCount     int64               `json:"subUserCount"`     // 下级用户数量
	CustomerCount    int64               `json:"customerCount"`    // 客户数量
	TransactionCount int64               `json:"transactionCount"` // 交易笔数
	CurrencyStats    []CurrencyStat      `json:"currencyStats"`    // 币种统计
	MonthlyStats     []MonthlyStat       `json:"monthlyStats"`     // 月度统计
	SubUsers         []SubUserReportData `json:"subUsers"`         // 下级用户报表
}

type SummaryInfo struct {
	TotalBalance string `json:"totalBalance"`
	TotalFrozen  string `json:"totalFrozen"`
	Symbol       string `json:"symbol"`
}

type TransactionBrief struct {
	Id        int64  `json:"id"`
	Type      string `json:"type"`
	Amount    string `json:"amount"`
	Symbol    string `json:"symbol"`
	CreatedAt int64  `json:"createdAt"`
}

type TransactionDetail struct {
	Id        int64  `json:"id"`
	Type      string `json:"type"`
	Amount    string `json:"amount"`
	Symbol    string `json:"symbol"`
	CreatedAt int64  `json:"createdAt"`
	Note      string `json:"note,optional"`
}

type TransactionListData struct {
	Total int64              `json:"total"`
	List  []TransactionBrief `json:"list"`
}

type UpdateCustomerReq struct {
	Id              int64  `path:"id"`                       // 客户ID
	FirstName       string `json:"firstName,optional"`       // 名
	LastName        string `json:"lastName,optional"`        // 姓
	Phone           string `json:"phone,optional"`           // 电话
	Email           string `json:"email,optional"`           // 邮箱
	Address         string `json:"address,optional"`         // 地址
	IdNumber        string `json:"idNumber,optional"`        // 身份证
	BusinessLicense string `json:"businessLicense,optional"` // 营业执照
}

type UpdateFeeSettingsReq struct {
	ExchangeFeeRate string `json:"exchangeFeeRate"` // 换汇手续费率 如0.0600
	WithdrawFee     string `json:"withdrawFee"`     // 提现手续费 如2.00
}

type UpdateInviteReq struct {
	Id              int64   `path:"id"`              // 邀请ID
	ExchangeFeeRate string  `json:"exchangeFeeRate"` // 换汇手续费率
	WithdrawFee     string  `json:"withdrawFee"`     // 提现手续费
	CountryIds      []int64 `json:"countryIds"`      // 授权国家ID列表
	Remark          string  `json:"remark,optional"` // 备注
}

type UpdateProfileReq struct {
	Email string `json:"email,optional"` // 邮箱
	Name  string `json:"name,optional"`  // 名称
}

type UpdateUserCountryAuthReq struct {
	Id         int64   `path:"id"`         // 用户ID
	CountryIds []int64 `json:"countryIds"` // 国家ID列表
}

type UpdateUserFeesReq struct {
	Id              int64  `path:"id"`              // 用户ID
	ExchangeFeeRate string `json:"exchangeFeeRate"` // 换汇手续费率
	WithdrawFee     string `json:"withdrawFee"`     // 提现手续费
}

type UserInfo struct {
	Id                  int64         `json:"id"`                  // ID
	UserType            string        `json:"userType"`            // 用户类型
	ParentId            int64         `json:"parentId"`            // 父级用户ID
	ParentTree          string        `json:"parentTree"`          // 父级用户树
	Email               string        `json:"email"`               // 邮箱
	InviteCode          string        `json:"inviteCode"`          // 邀请码
	ExchangeFeeRate     string        `json:"exchangeFeeRate"`     // 换汇手续费率
	WithdrawFee         string        `json:"withdrawFee"`         // 提现手续费
	Status              int32         `json:"status"`              // 状态
	CreatedAt           int64         `json:"createdAt"`           // 创建时间
	UpdatedAt           int64         `json:"updatedAt"`           // 更新时间
	AuthorizedCountries []CountryInfo `json:"authorizedCountries"` // 授权国家列表
}

type UserListData struct {
	Total int64      `json:"total"` // 总记录数
	List  []UserInfo `json:"list"`  // 列表
}

type WalletBalanceInfo struct {
	Available string `json:"available"` // 可用余额
	Frozen    string `json:"frozen"`    // 冻结余额
	Symbol    string `json:"symbol"`    // 币种
}

type WalletBrief struct {
	Id         int64  `json:"id"`         // 钱包ID
	CustomerId int64  `json:"customerId"` // 客户ID
	Symbol     string `json:"symbol"`     // 币种
	CreatedAt  int64  `json:"createdAt"`  // 创建时间
}

type WalletDetail struct {
	Id         int64  `json:"id"`
	CustomerId int64  `json:"customerId"`
	Symbol     string `json:"symbol"`
	CreatedAt  int64  `json:"createdAt"`
}

type WalletListData struct {
	Total int64         `json:"total"`
	List  []WalletBrief `json:"list"`
}

type WithdrawalInfo struct {
	Id        int64  `json:"id"`
	WalletId  int64  `json:"walletId"`
	AddressId int64  `json:"addressId"`
	Amount    string `json:"amount"`
	Symbol    string `json:"symbol"`
	Status    int32  `json:"status"`
	CreatedAt int64  `json:"createdAt"`
}

type WithdrawalListData struct {
	Total int64            `json:"total"`
	List  []WithdrawalInfo `json:"list"`
}
